# Site settings
title: Jekyll-Uno
description: 'Jason's Blog - Running on Jekyll-Uno'
url: 'https://jasonmorgan.github.io'
baseurl: '/'
enforce_ssl: 'jasonmorgan.github.io'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jason Morgan'
  email: jmorgan@f9vs.com
  twitter_username: rjasonmorgan
  facebook_username: rjasonmorgan
  github_username:  jasonmorgan
  linkedin_username:  jasonmorgan2

# Build settings
destination: _site
paginate: 10
permalink: /:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: 
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-gist
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
